apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site
charts:
- name: istio-operator
  override:
    revision: "1-9-1"
    operator.resources.limits.cpu: 200m
    operator.resources.limits.memory: 256Mi
    operator.resources.requests.cpu: 50m
    operator.resources.requests.memory: 128Mi

- name: jaeger-operator
  override:
    jaeger.spec.storage.options.es:
      server-urls: https://eck-elasticsearch-es-http:9200
      username: elastic
      password: tacoword

- name: service-mesh-controlplane
  override:
    IstioOperator.revision: "1-9-1"
    IstioOperator.meshConfig.enableTracing: true
    IstioOperator.meshConfig.tracingSampling: 100
    IstioOperator.meshConfig.tracingUrl: jaeger-operator-jaeger-collector.lma.svc:9411

- name: service-mesh-gateway
  override:
    IstioOperator.ingressGateways:
      - name: default
        resources:
          requests_cpu: 1000m
          requests_memory: 1024Mi
          limits_cpu: 2000m
          limits_memory: 2048Mi
        hpaMaxReplicas: 10
        hpaTargetCpuUtilization: 80
        serviceType: NodePort
    IstioOperator.egressGateways: []
